# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b07d04fd9ad94c06846125056ad1e6e41a507e76cc737ada21b841ee4be662a66525f4558a15530f351adb75d81cbd97aafca2967f78044ebc7498d3b1e92fd

test:
  secret_key_base: 98437e38aa3e2d237b8fd49502bae61fc4bfe23366013dede87b4bb42ae5a6334b6ca04b47efed1903be272baf09f92a75d80580fb97dec4133bb07e764cbe82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
